// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Moonlay.Topics
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class MessageHeader : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""MessageHeader"",""namespace"":""Moonlay.Topics"",""fields"":[{""name"":""Token"",""type"":""string""},{""name"":""CurrentUser"",""type"":""string""},{""name"":""IsCurrentUserDemo"",""type"":""boolean""},{""name"":""AppOrigin"",""type"":""string""},{""name"":""Timestamp"",""type"":""string""}]}");
		private string _Token;
		private string _CurrentUser;
		private bool _IsCurrentUserDemo;
		private string _AppOrigin;
		private string _Timestamp;
		public virtual Schema Schema
		{
			get
			{
				return MessageHeader._SCHEMA;
			}
		}
		public string Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				this._Token = value;
			}
		}
		public string CurrentUser
		{
			get
			{
				return this._CurrentUser;
			}
			set
			{
				this._CurrentUser = value;
			}
		}
		public bool IsCurrentUserDemo
		{
			get
			{
				return this._IsCurrentUserDemo;
			}
			set
			{
				this._IsCurrentUserDemo = value;
			}
		}
		public string AppOrigin
		{
			get
			{
				return this._AppOrigin;
			}
			set
			{
				this._AppOrigin = value;
			}
		}
		public string Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Token;
			case 1: return this.CurrentUser;
			case 2: return this.IsCurrentUserDemo;
			case 3: return this.AppOrigin;
			case 4: return this.Timestamp;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Token = (System.String)fieldValue; break;
			case 1: this.CurrentUser = (System.String)fieldValue; break;
			case 2: this.IsCurrentUserDemo = (System.Boolean)fieldValue; break;
			case 3: this.AppOrigin = (System.String)fieldValue; break;
			case 4: this.Timestamp = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
